import { describe, expect, test } from "bun:test";
import { spawn } from "bun";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "../..");
const AGENTS_MD = path.join(REPO_ROOT, "AGENTS.md");

describe("AGENTS.md generator (S53.7)", () => {
  test("the on-disk AGENTS.md matches what the generator emits", async () => {
    const proc = spawn(["bun", "run", "scripts/gen-agents-md.ts", "--check"], {
      cwd: REPO_ROOT,
      stdout: "pipe",
      stderr: "pipe",
    });
    const [stdout, stderr, exitCode] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ]);
    expect(
      exitCode,
      `gen-agents-md --check failed:\n${stderr || stdout}\n` +
        `Run \`bun run gen:agents-md\` and commit AGENTS.md.`,
    ).toBe(0);
  });

  test("AGENTS.md carries the autogen header + identity sentence", async () => {
    const body = await readFile(AGENTS_MD, "utf8");
    expect(body).toContain("AUTOGENERATED");
    expect(body).toContain("scaffold-day docs --for-ai");
    expect(body).toContain("**Identity.**");
    expect(body).toContain("## JTBD → call flow");
    expect(body).toContain("## CLI commands");
    expect(body).toContain("## MCP tools");
    // Markdown render doesn't include `home`, but make sure the
    // generator's machine path didn't leak through some other route.
    expect(body).not.toContain("/Users/");
    expect(body).not.toContain("/home/");
  });
});
