import { describe, expect, test } from "bun:test";
import { spawn } from "bun";
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "../..");
const CLI_DIR = path.join(REPO_ROOT, "apps/web/content/cli");

describe("CLI reference MDX (S53.8)", () => {
  test("the on-disk MDX tree matches what the generator emits", async () => {
    const proc = spawn(["bun", "run", "scripts/gen-cli-reference.ts", "--check"], {
      cwd: REPO_ROOT,
      stdout: "pipe",
      stderr: "pipe",
    });
    const [stdout, stderr, exitCode] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ]);
    expect(
      exitCode,
      `gen-cli-reference --check failed:\n${stderr || stdout}\n` +
        `Run \`bun run gen:cli-reference\` and commit the diff.`,
    ).toBe(0);
  });

  test("every registered command has a corresponding .mdx", async () => {
    const files = (await readdir(CLI_DIR)).filter((n) => n.endsWith(".mdx"));
    // _index plus one per command
    expect(files).toContain("_index.mdx");
    expect(files).toContain("today.mdx");
    expect(files).toContain("docs.mdx");
    expect(files).toContain("place.mdx");
    expect(files.length).toBeGreaterThanOrEqual(15);
  });

  test("every per-command MDX renders the 6-section template + autogen header", async () => {
    const files = (await readdir(CLI_DIR)).filter(
      (n) => n.endsWith(".mdx") && n !== "_index.mdx",
    );
    for (const name of files) {
      const body = await readFile(path.join(CLI_DIR, name), "utf8");
      expect(body, `${name} missing autogen header`).toContain("AUTOGENERATED");
      expect(body, `${name} missing frontmatter title`).toContain("title: scaffold-day");
      expect(body, `${name} missing WHAT`).toContain("## WHAT");
      expect(body, `${name} missing WHEN`).toContain("## WHEN");
      expect(body, `${name} missing COST`).toContain("## COST");
      expect(body, `${name} missing INPUT`).toContain("## INPUT");
      expect(body, `${name} missing RETURN`).toContain("## RETURN");
      expect(body, `${name} missing GOTCHA`).toContain("## GOTCHA");
    }
  });

  test("_index.mdx links to every per-command page", async () => {
    const index = await readFile(path.join(CLI_DIR, "_index.mdx"), "utf8");
    const files = (await readdir(CLI_DIR)).filter(
      (n) => n.endsWith(".mdx") && n !== "_index.mdx",
    );
    for (const name of files) {
      const slug = name.replace(/\.mdx$/, "");
      expect(index, `_index.mdx missing link for ${slug}`).toContain(`./${slug}`);
    }
  });
});
