import { describe, expect, test } from "bun:test";
import { isScaffoldError } from "../error";
import { BALANCED_PRESET } from "./balanced-preset";
import {
  applyPolicyPatchPreservingFormatting,
  compilePolicy,
  diffPolicy,
  serializePolicy,
} from "./yaml-codec";

const SAMPLE_YAML_WITH_COMMENTS = `# scaffold-day policy — keep your comments, they survive patches.
schema_version: "0.1.0"
preset: balanced

context:
  # Asia/Seoul because the user lives in KST.
  tz: Asia/Seoul
  working_hours:
    - { start: "09:00", end: "18:00", days: [mon, tue, wed, thu, fri] }
  energy_peaks: []
  protected_ranges:
    # No placement during lunch.
    - { start: "12:00", end: "13:00", label: lunch, days: [mon, tue, wed, thu, fri] }

hard_rules:
  - { kind: no_placement_in, start: "22:00", end: "07:00" }
  - { kind: min_buffer_around_meeting_min, minutes: 10 }

soft_preferences:
  - { kind: cluster_same_tag, weight: 8 }

reactivity: balanced
importance_weights:
  urgency: 1.5
  impact: 2.0
  effort: 0.8
  reversibility: 1.0
  time_sensitivity: 0
  external_dependency: 0
  hard_deadline_bonus: 15
  soft_deadline_bonus: 8
  external_dependency_bonus: 5
conflict_thresholds:
  auto_resolve_max_score: 40
  decisive_gap_score: 20
placement_grid_min: 30
`;

describe("compilePolicy", () => {
  test("parses commented YAML to a validated Policy", () => {
    const policy = compilePolicy(SAMPLE_YAML_WITH_COMMENTS);
    expect(policy.context.tz).toBe("Asia/Seoul");
    expect(policy.placement_grid_min).toBe(30);
    expect(policy.hard_rules).toHaveLength(2);
  });

  test("rejects malformed YAML with DAY_INVALID_INPUT", () => {
    let caught: unknown;
    try {
      compilePolicy("[unbalanced\n");
    } catch (e) {
      caught = e;
    }
    expect(isScaffoldError(caught)).toBe(true);
    if (isScaffoldError(caught)) expect(caught.code).toBe("DAY_INVALID_INPUT");
  });

  test("rejects YAML that fails Zod (missing context)", () => {
    let caught: unknown;
    try {
      compilePolicy("placement_grid_min: 30\n");
    } catch (e) {
      caught = e;
    }
    expect(isScaffoldError(caught)).toBe(true);
    if (isScaffoldError(caught)) expect(caught.code).toBe("DAY_INVALID_INPUT");
  });
});

describe("serializePolicy + compilePolicy round-trip (no source comments)", () => {
  test("Balanced preset → YAML → Policy survives", () => {
    const yamlText = serializePolicy(BALANCED_PRESET);
    const back = compilePolicy(yamlText);
    expect(back).toEqual(BALANCED_PRESET);
  });

  test("headerComment is rendered as YAML comment", () => {
    const yamlText = serializePolicy(BALANCED_PRESET, {
      headerComment: "Generated by scaffold-day preset apply balanced",
    });
    expect(yamlText.startsWith("# Generated by scaffold-day preset apply balanced")).toBe(
      true,
    );
  });
});

describe("diffPolicy + applyPolicyPatchPreservingFormatting", () => {
  test("comment-bearing YAML stays comment-bearing after a JSON Patch", () => {
    const before = compilePolicy(SAMPLE_YAML_WITH_COMMENTS);
    const after = { ...before, placement_grid_min: 15 };
    const patch = diffPolicy(before, after);
    expect(patch.length).toBeGreaterThan(0);

    const patchedYaml = applyPolicyPatchPreservingFormatting(
      SAMPLE_YAML_WITH_COMMENTS,
      patch,
    );

    // Comments survived.
    expect(patchedYaml).toContain("# scaffold-day policy");
    expect(patchedYaml).toContain("# Asia/Seoul because the user lives in KST.");
    expect(patchedYaml).toContain("# No placement during lunch.");

    // Value changed.
    expect(patchedYaml).toMatch(/placement_grid_min:\s*15/);
    expect(patchedYaml).not.toMatch(/placement_grid_min:\s*30/);

    // Patched YAML still validates.
    const recompiled = compilePolicy(patchedYaml);
    expect(recompiled.placement_grid_min).toBe(15);
  });

  test("nested replace preserves siblings and comments", () => {
    const before = compilePolicy(SAMPLE_YAML_WITH_COMMENTS);
    const after = {
      ...before,
      importance_weights: { ...before.importance_weights, urgency: 3.0 },
    };
    const patch = diffPolicy(before, after);
    const patchedYaml = applyPolicyPatchPreservingFormatting(
      SAMPLE_YAML_WITH_COMMENTS,
      patch,
    );
    expect(patchedYaml).toContain("# Asia/Seoul because the user lives in KST.");
    expect(patchedYaml).toMatch(/urgency:\s*3/);
    expect(patchedYaml).toMatch(/impact:\s*2/);
  });

  test("array remove drops a hard rule but keeps surrounding comments", () => {
    const before = compilePolicy(SAMPLE_YAML_WITH_COMMENTS);
    const after = {
      ...before,
      hard_rules: before.hard_rules.slice(1), // drop first
    };
    const patch = diffPolicy(before, after);
    const patchedYaml = applyPolicyPatchPreservingFormatting(
      SAMPLE_YAML_WITH_COMMENTS,
      patch,
    );
    expect(patchedYaml).toContain("# scaffold-day policy");
    const recompiled = compilePolicy(patchedYaml);
    expect(recompiled.hard_rules).toHaveLength(1);
    expect(recompiled.hard_rules[0]?.kind).toBe("min_buffer_around_meeting_min");
  });

  test("rejects unsupported ops (move/copy)", () => {
    let caught: unknown;
    try {
      applyPolicyPatchPreservingFormatting(SAMPLE_YAML_WITH_COMMENTS, [
        { op: "move", from: "/preset", path: "/preset_renamed" },
      ]);
    } catch (e) {
      caught = e;
    }
    expect(isScaffoldError(caught)).toBe(true);
    if (isScaffoldError(caught)) expect(caught.code).toBe("DAY_INVALID_INPUT");
  });

  test("rejects patch that breaks the schema", () => {
    let caught: unknown;
    try {
      applyPolicyPatchPreservingFormatting(SAMPLE_YAML_WITH_COMMENTS, [
        { op: "remove", path: "/context/tz" },
      ]);
    } catch (e) {
      caught = e;
    }
    expect(isScaffoldError(caught)).toBe(true);
    if (isScaffoldError(caught)) expect(caught.code).toBe("DAY_INVALID_INPUT");
  });

  test("empty patch returns the YAML unchanged byte-for-byte (round-trip via Document)", () => {
    const patched = applyPolicyPatchPreservingFormatting(
      SAMPLE_YAML_WITH_COMMENTS,
      [],
    );
    // Byte-for-byte may differ in trailing newline; structural equality.
    const a = compilePolicy(patched);
    const b = compilePolicy(SAMPLE_YAML_WITH_COMMENTS);
    expect(a).toEqual(b);
    expect(patched).toContain("# scaffold-day policy");
  });
});
