#!/usr/bin/env bun
/**
 * Generate `AGENTS.md` at the repo root from the canonical
 * `scaffold-day docs --for-ai --format markdown` bundle (§S53.7).
 *
 * `AGENTS.md` is the single instruction file an AI client (Claude Code,
 * Cursor, Claude Desktop) reads at session start. We commit it to the
 * repo so:
 *   1. Forks ship the same default surface description.
 *   2. CI gates a stale `AGENTS.md` (the file must match what the
 *      generator would emit right now).
 *
 * Modes:
 *   default       — write `AGENTS.md` (idempotent, safe to commit)
 *   --check       — exit 1 if the on-disk file differs from the bundle
 *                   (used in CI to keep AGENTS.md fresh)
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { commands } from "../packages/day-cli/src/cli/registry";
import { buildBundle, renderMarkdown } from "../packages/day-cli/src/commands/docs-bundle";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "..");
const AGENTS_MD = path.join(REPO_ROOT, "AGENTS.md");

const HEADER = [
  "<!-- AUTOGENERATED by `bun run gen:agents-md`. Do not edit by hand. -->",
  "<!-- Source: `scaffold-day docs --for-ai --format markdown` (SLICES §S53.7). -->",
  "",
].join("\n");

function generate(): string {
  // Pin the embedded `home` path: defaultHomeDir() resolves $HOME on the
  // generator's machine, which would otherwise drift between contributors.
  const bundle = buildBundle({
    commands,
    filterCli: null,
    scope: "all",
    home: "<SCAFFOLD_DAY_HOME or ~/.scaffold-day>",
  });
  return `${HEADER}${renderMarkdown(bundle)}\n`;
}

async function main(): Promise<number> {
  const args = process.argv.slice(2);
  const check = args.includes("--check");
  const next = generate();

  if (check) {
    let prev = "";
    try {
      prev = await readFile(AGENTS_MD, "utf8");
    } catch {
      console.error(`✗ AGENTS.md missing at ${AGENTS_MD}`);
      console.error("  run: bun run gen:agents-md");
      return 1;
    }
    if (prev !== next) {
      console.error("✗ AGENTS.md is stale (source: scaffold-day docs --for-ai)");
      console.error("  run: bun run gen:agents-md && git add AGENTS.md");
      return 1;
    }
    console.log(`✓ AGENTS.md up to date (${next.length} chars)`);
    return 0;
  }

  await writeFile(AGENTS_MD, next, "utf8");
  console.log(`→ wrote AGENTS.md (${next.length} chars)`);
  return 0;
}

const code = await main();
process.exit(code);
