#!/usr/bin/env bun
/**
 * Generate one MDX file per CLI command from its registered `--help`
 * 6-section template (§S53.8).
 *
 * Output: `apps/web/content/cli/<command>.mdx` plus an `_index.mdx`
 * listing every command. The docs site (S52/S53) renders these as the
 * canonical CLI reference; CI gates a stale tree.
 *
 * Modes:
 *   default  — write the MDX tree (idempotent)
 *   --check  — exit 1 if any file on disk diverges from the generator
 */
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { commands } from "../packages/day-cli/src/cli/registry";
import type { Command } from "../packages/day-cli/src/cli/command";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "..");
const OUT_DIR = path.join(REPO_ROOT, "apps/web/content/cli");
const HEADER =
  "{/* AUTOGENERATED by `bun run gen:cli-reference`. Do not edit by hand. */}\n" +
  "{/* Source: registry + 6-section help (SLICES §S53.8). */}\n";

function escapeMdx(text: string): string {
  // Backticks in the help body are kept; MDX renders them as inline code.
  // Curly braces collide with JSX expressions, so escape them.
  return text.replace(/{/g, "&#123;").replace(/}/g, "&#125;");
}

function commandToMdx(cmd: Command): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push(`title: scaffold-day ${cmd.name}`);
  lines.push(`description: ${JSON.stringify(cmd.summary)}`);
  lines.push(`command: ${cmd.name}`);
  lines.push("---");
  lines.push("");
  lines.push(HEADER);
  lines.push(`# \`scaffold-day ${cmd.name}\``);
  lines.push("");
  lines.push(`> ${escapeMdx(cmd.summary)}`);
  lines.push("");
  lines.push("## WHAT");
  lines.push("");
  lines.push(escapeMdx(cmd.help.what));
  lines.push("");
  lines.push("## WHEN");
  lines.push("");
  lines.push(escapeMdx(cmd.help.when));
  lines.push("");
  lines.push("## COST");
  lines.push("");
  lines.push(escapeMdx(cmd.help.cost));
  lines.push("");
  lines.push("## INPUT");
  lines.push("");
  lines.push("```");
  lines.push(cmd.help.input);
  lines.push("```");
  lines.push("");
  lines.push("## RETURN");
  lines.push("");
  lines.push(escapeMdx(cmd.help.return));
  lines.push("");
  lines.push("## GOTCHA");
  lines.push("");
  lines.push(escapeMdx(cmd.help.gotcha));
  lines.push("");
  return lines.join("\n");
}

function indexMdx(cmds: Command[]): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push("title: CLI reference");
  lines.push('description: "Every scaffold-day CLI command, generated from --help."');
  lines.push("---");
  lines.push("");
  lines.push(HEADER);
  lines.push("# CLI reference");
  lines.push("");
  lines.push(
    "Auto-generated from the registry's 6-section help template. Run `scaffold-day docs --for-ai` for the AI-bundle equivalent.",
  );
  lines.push("");
  lines.push("| Command | Summary |");
  lines.push("| --- | --- |");
  for (const c of cmds) {
    lines.push(`| [\`${c.name}\`](./${c.name}) | ${escapeMdx(c.summary)} |`);
  }
  lines.push("");
  return lines.join("\n");
}

type FileMap = Map<string, string>;

function generate(): FileMap {
  const map: FileMap = new Map();
  for (const cmd of commands) {
    map.set(`${cmd.name}.mdx`, commandToMdx(cmd));
  }
  map.set("_index.mdx", indexMdx(commands));
  return map;
}

async function readTree(dir: string): Promise<FileMap> {
  const map: FileMap = new Map();
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    return map;
  }
  for (const name of entries) {
    if (!name.endsWith(".mdx")) continue;
    map.set(name, await readFile(path.join(dir, name), "utf8"));
  }
  return map;
}

function diff(prev: FileMap, next: FileMap): { changed: string[]; missing: string[]; extra: string[] } {
  const changed: string[] = [];
  const missing: string[] = [];
  const extra: string[] = [];
  for (const [name, content] of next) {
    const before = prev.get(name);
    if (before === undefined) missing.push(name);
    else if (before !== content) changed.push(name);
  }
  for (const name of prev.keys()) {
    if (!next.has(name)) extra.push(name);
  }
  return { changed, missing, extra };
}

async function main(): Promise<number> {
  const args = process.argv.slice(2);
  const check = args.includes("--check");
  const next = generate();

  if (check) {
    const prev = await readTree(OUT_DIR);
    const d = diff(prev, next);
    const stale = d.changed.length + d.missing.length + d.extra.length;
    if (stale > 0) {
      console.error(`✗ CLI reference tree is stale (${stale} files differ)`);
      if (d.missing.length > 0) console.error(`  missing: ${d.missing.join(", ")}`);
      if (d.changed.length > 0) console.error(`  changed: ${d.changed.join(", ")}`);
      if (d.extra.length > 0) console.error(`  extra:   ${d.extra.join(", ")}`);
      console.error(`  run: bun run gen:cli-reference && git add ${path.relative(REPO_ROOT, OUT_DIR)}`);
      return 1;
    }
    console.log(`✓ CLI reference tree up to date (${next.size} files)`);
    return 0;
  }

  await mkdir(OUT_DIR, { recursive: true });
  // Drop any stale .mdx that no longer corresponds to a registered
  // command (e.g., a renamed command).
  for (const name of (await readdir(OUT_DIR).catch(() => []))) {
    if (name.endsWith(".mdx") && !next.has(name)) {
      await rm(path.join(OUT_DIR, name));
    }
  }
  for (const [name, content] of next) {
    await writeFile(path.join(OUT_DIR, name), content, "utf8");
  }
  console.log(`→ wrote ${next.size} mdx files to ${path.relative(REPO_ROOT, OUT_DIR)}/`);
  return 0;
}

const code = await main();
process.exit(code);
